-- 逐患者查询索引 (幂等)。调用方必须同时用 -d 与 -v 显式选择同一目标库:
-- sqlcmd <连接参数> -d TP_data_hub -v HUB_DATABASE=TP_data_hub -b -i scripts/sql/create_data_hub_indexes.sql
-- 工作台 HubRawSource 按 JZLSH 单患者取数 + fee⋈EXT / LIS 指标⋈报告 join 键.
-- 只加索引不动数据; 回滚 = DROP INDEX 同名.
-- 142 sh_yb_platform 由 DE 维护且 Javert 只读；其索引由 DE/DBA 用同一校验方式执行。
:on error exit
IF DB_NAME() <> N'$(HUB_DATABASE)'
    THROW 51000, N'目标数据库与 HUB_DATABASE 不一致，拒绝建索引', 1;
GO

-- v2.2: 费用 EXT 恢复 (IX_EXT_YQ_SFMXID 回归); IX_SYSSK_EXT_KEY 保持移除 (SYSSK_EXT 已删不恢复)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FS_JZLSH')
    CREATE NONCLUSTERED INDEX IX_FS_JZLSH ON TB_HIS_ZY_FEE_DETAIL_FS (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_EXT_YQ_SFMXID')
    CREATE NONCLUSTERED INDEX IX_EXT_YQ_SFMXID ON TB_HIS_ZY_FEE_DETAIL_EXT (YLJGYQDM, SFMXID);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_DOC_JZLSH')
    CREATE NONCLUSTERED INDEX IX_DOC_JZLSH ON TB_CIS_MEDICAL_DOCUMENT (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_ZD_JZLSH')
    CREATE NONCLUSTERED INDEX IX_ZD_JZLSH ON TB_IH_DIAGNOSIS_DETAIL (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SS_JZLSH')
    CREATE NONCLUSTERED INDEX IX_SS_JZLSH ON TB_OPRATION_DETAIL (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_LISRPT_JZLSH')
    CREATE NONCLUSTERED INDEX IX_LISRPT_JZLSH ON TB_LIS_REPORT (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_LISIND_JOIN')
    CREATE NONCLUSTERED INDEX IX_LISIND_JOIN ON TB_LIS_INDICATORS (YLJGYQDM, BGDH, BGRQ);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RIS_JZLSH')
    CREATE NONCLUSTERED INDEX IX_RIS_JZLSH ON TB_RIS_REPORT (JZLSH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_RIS2_JZLSH')
    CREATE NONCLUSTERED INDEX IX_RIS2_JZLSH ON TB_RIS_REPORT2 (JZLSH);

-- harden-onsite-redlines Task 5.3: BA 病案首页四表 (szx fetch_zd/fetch_ss 按
-- (YLJGYQDM, SYXH) 逐患者查; SYZDK.ZDDM 供 ZYZD 码→名字典解析)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYJBK_YQ_SYXH')
    CREATE NONCLUSTERED INDEX IX_SYJBK_YQ_SYXH ON TB_BA_SYJBK (YLJGYQDM, SYXH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYZDK_YQ_SYXH')
    CREATE NONCLUSTERED INDEX IX_SYZDK_YQ_SYXH ON TB_BA_SYZDK (YLJGYQDM, SYXH);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYZDK_ZDDM')
    CREATE NONCLUSTERED INDEX IX_SYZDK_ZDDM ON TB_BA_SYZDK (ZDDM);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_SYSSK_YQ_SYXH')
    CREATE NONCLUSTERED INDEX IX_SYSSK_YQ_SYXH ON TB_BA_SYSSK (YLJGYQDM, SYXH);
